name: Playwright + Argos Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-e2es:
    if: contains(github.event.pull_request.labels.*.name, 'visual testing new')
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.1-noble

    steps:
      - uses: actions/checkout@v4

      - uses: bahmutov/npm-install@v1

      - uses: actions/setup-node@v3

      - name: Run tests
        run: npx playwright test
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
