name: Run Visual Testing on PR comment

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  visial-testing:
    if: contains(github.event.pull_request.labels.*.name, 'visual testing')
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.1-noble

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - uses: bahmutov/npm-install@v1

      - run: npm run test:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PULL_REQUEST: ${{ github.event.pull_request.number }}
