name: Playwright + Argos Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  run-e2es:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.1-noble

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npx playwright test
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
