name: Run Visual Testing on Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

env:
  NODE_VERSION: 20.x

jobs:
  visial-testing:
    if: contains(github.event.pull_request.labels.*.name, 'visual testing')
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.1-noble
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: bahmutov/npm-install@v1

      - name: Install Playwright browsers and dependencies
        run: npx playwright install --with-deps

      - run: npm run test:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
